//// Generated by spider on 2020-04-24 04:20:28.476647

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:kuvaton_client_flutter/res/images.dart';

void main() {
  test('images assets test', () {
    expect(true, File(Images.kuvatonComLogoUusi).existsSync());
  });
}
